#!/usr/bin/env bash

set -euo pipefail

die () { echo $1 >&2; exit 1; }

here="$(dirname "$0")"
root=$here/..
tmpfile="$(mktemp)"
timestamp="$(date +%s)"
curl -fsS -o "$tmpfile" "https://eiapi.tcl.sh/legendaries/report?token=${EIAPI_TOKEN}&public=1"
[[ -s $tmpfile ]] || die 'API request succeeded but response is empty'
mv "$tmpfile" "$root/public/reports/${timestamp}.txt"
