name: build
on:
  push:
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Initialize dependencies
        run: |
          make init
      - name: Download database backup
        run: |
          scripts/fetch-database-backup
        env:
          EIAPI_TOKEN: ${{ secrets.EIAPI_TOKEN }}
      - name: Build
        run: |
          make
      - name: Install netlify cli
        run: |
          npm install -g netlify-cli
      - name: Preview
        run: |
          netlify deploy --alias "${GITHUB_REF##*/}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: github.ref != 'refs/heads/master'
      - name: Preview
        run: |
          netlify deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: github.ref != 'refs/heads/master'
      - name: Deploy
        run: |
          netlify deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: github.ref == 'refs/heads/master'
