name: fetch new report
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch new report
        run: |
          scripts/fetch-new-report
        env:
          EIAPI_TOKEN: ${{ secrets.EIAPI_TOKEN }}
      - name: Commit, push changes, and trigger new build
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add public/reports
          git commit -m 'reports: add new report (from GitHub Actions)'
          git push
          # Use a separate personal access token since the token included doesn't seem to trigger
          # anything, although the response (HTTP 204) looks all right.
          curl -fsS -D- \
            -X POST \
            -H 'Authorization: Bearer ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
            -d '{"ref": "'${GITHUB_REF##*/}'"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
